project:
  type: website
  output-dir: docs
  render:
    - "404.qmd"
    - "index.qmd"
    - "resources.qmd"
    - "schedule.qmd"
    - "syllabus.qmd"
    - "exercises/sem_1.qmd"
    - "exercises/sem_2.qmd"  # don't know what happen there :oo:
    - "dm/01-dm.qmd"
  resources:
    - "slides/cours_1.html"
    - "slides/cours_1_files/"
    - "slides/cours_2.html"
    - "slides/cours_2_files/"
    - "slides/images/"
    - "material/semaine_1.zip"
    - "material/semaine_2.zip"
  #   - "slides/img/"
  #   - "slides/libs/"
  #   - "slides/css/"
  #   - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

# bibliography: files/bib/references.bib
# csl: files/bib/chicago-author-date.csl
description-meta: "R avancé et introduction à Git"

website:
  title: "R avancé et introduction à Git"
  site-url: "https://rnedellec-r-advanced-git.netlify.app/"
  favicon: "html/RN.png"

  navbar:
    pinned: true
    background: "#3B8686"
    right:
      - text: "Objectifs"
        file: syllabus.qmd
      - text: "Agenda"
        file: schedule.qmd
      - text: "Ressources"
        file: resources.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})
format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai