---
format: html
---

## Agenda du cours

- L'objectif de la première session sera de faire un rappel des notions de programmation en R et de bien configurer son environnement de développement avec Rstudio.
- Lors de la seconde session, nous nous concentrerons sur l'écriture de fonctions, et nous introduirons les objets S3, et les classes les plus importantes. 
- Lors de la troisième séance, nous nous intéresserons à la créations de librairies R.
- Lors de la quatrième session, nous nous initierons à la programmation littéraire et aux outils de la science reproductible avec l'outil quarto et le package targets.
- Enfin, lors de la cinquième séance, nous ferons une introduction à git, et à la plateforme github.

## Matériel et supports de cours



| Date       | Objectifs                                             | Cours                                   | Exercices                                               | Input                                     |
|------------|-------------------------------------------------------|:---------------------------------------:|:-------------------------------------------------------:|:-----------------------------------------:|
| 6 janvier  | **Configuration de l'IDE Rstudio, Rappels de R**      | [{{< fa book >}}](/slides/cours_1.html) | [{{< fa file-circle-question >}}](/exercises/sem_1.pdf) | [{{< fa box >}}](/material/semaine_1.zip) |
| 13 janvier | **Fonctions, Objets S3**                              | [{{< fa book >}}](/slides/cours_2.html) | [{{< fa file-circle-question >}}](/exercises/sem_2.pdf) | [{{< fa box >}}](/material/semaine_2.zip) |
| 19 janvier | **Rendu DM n°1**                                      |                                         | [{{< fa list-check >}}](/dm/01-dm.pdf)                  | [{{< fa box >}}](/material/dm_1.zip)      |
| 20 janvier | **Ecrire une librairie R**                            | [{{< fa book >}}](/slides/cours_3.html) | [{{< fa file-circle-question >}}](/exercises/sem_3.pdf) | [{{< fa box >}}](/material/semaine_3.zip) |
| 27 janvier | **Introduction à git et github**                      | [{{< fa book >}}](/slides/cours_4.html) | [{{< fa file-circle-question >}}](/exercises/sem_4.pdf) | [{{< fa box >}}](/material/semaine_4.zip) |
| 2 février  | **Rendu DM n°2**                                      |                                         | [{{< fa list-check >}}](/dm/02-dm.pdf)                  | [{{< fa box >}}](/material/dm_2.zip)      |
| 3 février  | **Programmation littéraire et science reproductible** | [{{< fa book >}}](/slides/cours_5.html) | [{{< fa file-circle-question >}}](/exercises/sem_5.pdf) | [{{< fa box >}}](/material/semaine_5.zip) |
| 10 février | **Projet final**                                      |                                         | [{{< fa list-check >}}](/dm/03-projet.pdf)              | [{{< fa box >}}](/material/projet.zip)    |


: {tbl-colwidths="\[15,55,10,10,15\]"}
